# Static ESG risk scores (higher = worse, based on Sustainalytics methodology)
# 0-10: Negligible, 10-20: Low, 20-30: Medium, 30-40: High, 40+: Severe

ESG_DATA = {
    # --- RETAIL / SHOPPING ---
    "walmart": {"score": 24, "rating": "Medium", "score_impact": 10},
    "amazon": {"score": 28, "rating": "Medium", "score_impact": 10},
    "target": {"score": 18, "rating": "Low", "score_impact": 5},
    "costco": {"score": 16, "rating": "Low", "score_impact": 5},
    "home depot": {"score": 22, "rating": "Medium", "score_impact": 10},
    "lowes": {"score": 23, "rating": "Medium", "score_impact": 10},
    "kroger": {"score": 26, "rating": "Medium", "score_impact": 10},
    "walgreens": {"score": 29, "rating": "Medium", "score_impact": 10},
    "cvs": {"score": 27, "rating": "Medium", "score_impact": 10},
    "dollar general": {"score": 32, "rating": "High", "score_impact": 20},
    "dollar tree": {"score": 31, "rating": "High", "score_impact": 20},
    "shein": {"score": 45, "rating": "Severe", "score_impact": 25},
    "fashion nova": {"score": 43, "rating": "Severe", "score_impact": 25},
    "tj maxx": {"score": 25, "rating": "Medium", "score_impact": 10},
    "marshalls": {"score": 25, "rating": "Medium", "score_impact": 10},
    "ross": {"score": 24, "rating": "Medium", "score_impact": 10},
    "macys": {"score": 28, "rating": "Medium", "score_impact": 10},
    "nordstrom": {"score": 19, "rating": "Low", "score_impact": 5},
    "gap": {"score": 30, "rating": "High", "score_impact": 20},
    "old navy": {"score": 30, "rating": "High", "score_impact": 20},
    "h&m": {"score": 32, "rating": "High", "score_impact": 20},
    "zara": {"score": 35, "rating": "High", "score_impact": 20},
    "forever 21": {"score": 40, "rating": "Severe", "score_impact": 25},
    "nike": {"score": 18, "rating": "Low", "score_impact": 5},
    "adidas": {"score": 17, "rating": "Low", "score_impact": 5},
    "under armour": {"score": 22, "rating": "Medium", "score_impact": 10},
    "best buy": {"score": 20, "rating": "Medium", "score_impact": 10},
    "ebay": {"score": 21, "rating": "Medium", "score_impact": 10},
    "etsy": {"score": 12, "rating": "Low", "score_impact": 5},
    "wayfair": {"score": 26, "rating": "Medium", "score_impact": 10},
    "ikea": {"score": 15, "rating": "Low", "score_impact": 5},
    "sephora": {"score": 18, "rating": "Low", "score_impact": 5},
    "ulta": {"score": 17, "rating": "Low", "score_impact": 5},
    "bath and body works": {"score": 22, "rating": "Medium", "score_impact": 10},
    "victorias secret": {"score": 33, "rating": "High", "score_impact": 20},
    "ralph lauren": {"score": 20, "rating": "Medium", "score_impact": 10},
    "coach": {"score": 19, "rating": "Low", "score_impact": 5},
    "louis vuitton": {"score": 18, "rating": "Low", "score_impact": 5},
    "lvmh": {"score": 18, "rating": "Low", "score_impact": 5},
    "gucci": {"score": 20, "rating": "Medium", "score_impact": 10},

    # --- FAST FOOD / RESTAURANTS ---
    "mcdonalds": {"score": 35, "rating": "High", "score_impact": 20},
    "starbucks": {"score": 22, "rating": "Medium", "score_impact": 10},
    "chick-fil-a": {"score": 34, "rating": "High", "score_impact": 20},
    "chick fil a": {"score": 34, "rating": "High", "score_impact": 20},
    "burger king": {"score": 33, "rating": "High", "score_impact": 20},
    "taco bell": {"score": 30, "rating": "High", "score_impact": 20},
    "wendys": {"score": 31, "rating": "High", "score_impact": 20},
    "subway": {"score": 28, "rating": "Medium", "score_impact": 10},
    "dominos": {"score": 25, "rating": "Medium", "score_impact": 10},
    "pizza hut": {"score": 29, "rating": "Medium", "score_impact": 10},
    "chipotle": {"score": 20, "rating": "Medium", "score_impact": 10},
    "dunkin": {"score": 24, "rating": "Medium", "score_impact": 10},
    "popeyes": {"score": 30, "rating": "High", "score_impact": 20},
    "kfc": {"score": 32, "rating": "High", "score_impact": 20},
    "sonic": {"score": 28, "rating": "Medium", "score_impact": 10},
    "dairy queen": {"score": 27, "rating": "Medium", "score_impact": 10},
    "five guys": {"score": 18, "rating": "Low", "score_impact": 5},
    "in n out": {"score": 15, "rating": "Low", "score_impact": 5},
    "shake shack": {"score": 16, "rating": "Low", "score_impact": 5},
    "panda express": {"score": 22, "rating": "Medium", "score_impact": 10},
    "olive garden": {"score": 24, "rating": "Medium", "score_impact": 10},
    "applebees": {"score": 26, "rating": "Medium", "score_impact": 10},
    "ihop": {"score": 25, "rating": "Medium", "score_impact": 10},
    "dennys": {"score": 26, "rating": "Medium", "score_impact": 10},
    "red lobster": {"score": 27, "rating": "Medium", "score_impact": 10},
    "outback steakhouse": {"score": 25, "rating": "Medium", "score_impact": 10},
    "cracker barrel": {"score": 30, "rating": "High", "score_impact": 20},
    "panera": {"score": 19, "rating": "Low", "score_impact": 5},
    "papa johns": {"score": 28, "rating": "Medium", "score_impact": 10},
    "little caesars": {"score": 24, "rating": "Medium", "score_impact": 10},

    # --- TECH COMPANIES ---
    "apple": {"score": 16, "rating": "Low", "score_impact": 5},
    "google": {"score": 24, "rating": "Medium", "score_impact": 10},
    "alphabet": {"score": 24, "rating": "Medium", "score_impact": 10},
    "microsoft": {"score": 14, "rating": "Low", "score_impact": 5},
    "meta": {"score": 36, "rating": "High", "score_impact": 20},
    "facebook": {"score": 36, "rating": "High", "score_impact": 20},
    "twitter": {"score": 38, "rating": "High", "score_impact": 20},
    "x": {"score": 38, "rating": "High", "score_impact": 20},
    "netflix": {"score": 18, "rating": "Low", "score_impact": 5},
    "uber": {"score": 32, "rating": "High", "score_impact": 20},
    "lyft": {"score": 28, "rating": "Medium", "score_impact": 10},
    "airbnb": {"score": 22, "rating": "Medium", "score_impact": 10},
    "tiktok": {"score": 40, "rating": "Severe", "score_impact": 25},
    "bytedance": {"score": 40, "rating": "Severe", "score_impact": 25},
    "snap": {"score": 26, "rating": "Medium", "score_impact": 10},
    "spotify": {"score": 15, "rating": "Low", "score_impact": 5},
    "adobe": {"score": 13, "rating": "Low", "score_impact": 5},
    "salesforce": {"score": 12, "rating": "Low", "score_impact": 5},
    "oracle": {"score": 22, "rating": "Medium", "score_impact": 10},
    "ibm": {"score": 18, "rating": "Low", "score_impact": 5},
    "intel": {"score": 20, "rating": "Medium", "score_impact": 10},
    "nvidia": {"score": 16, "rating": "Low", "score_impact": 5},
    "amd": {"score": 17, "rating": "Low", "score_impact": 5},
    "qualcomm": {"score": 19, "rating": "Low", "score_impact": 5},
    "cisco": {"score": 14, "rating": "Low", "score_impact": 5},
    "dell": {"score": 21, "rating": "Medium", "score_impact": 10},
    "hp": {"score": 18, "rating": "Low", "score_impact": 5},
    "samsung": {"score": 22, "rating": "Medium", "score_impact": 10},
    "sony": {"score": 16, "rating": "Low", "score_impact": 5},
    "paypal": {"score": 22, "rating": "Medium", "score_impact": 10},
    "square": {"score": 20, "rating": "Medium", "score_impact": 10},
    "shopify": {"score": 14, "rating": "Low", "score_impact": 5},
    "zoom": {"score": 18, "rating": "Low", "score_impact": 5},
    "slack": {"score": 15, "rating": "Low", "score_impact": 5},
    "dropbox": {"score": 16, "rating": "Low", "score_impact": 5},
    "twitter x": {"score": 38, "rating": "High", "score_impact": 20},
    "linkedin": {"score": 18, "rating": "Low", "score_impact": 5},
    "pinterest": {"score": 17, "rating": "Low", "score_impact": 5},
    "reddit": {"score": 24, "rating": "Medium", "score_impact": 10},
    "discord": {"score": 22, "rating": "Medium", "score_impact": 10},

    # --- BANKS & FINANCE ---
    "jpmorgan": {"score": 30, "rating": "High", "score_impact": 20},
    "jp morgan": {"score": 30, "rating": "High", "score_impact": 20},
    "bank of america": {"score": 28, "rating": "Medium", "score_impact": 10},
    "wells fargo": {"score": 38, "rating": "High", "score_impact": 20},
    "citibank": {"score": 32, "rating": "High", "score_impact": 20},
    "citigroup": {"score": 32, "rating": "High", "score_impact": 20},
    "goldman sachs": {"score": 34, "rating": "High", "score_impact": 20},
    "morgan stanley": {"score": 26, "rating": "Medium", "score_impact": 10},
    "american express": {"score": 20, "rating": "Medium", "score_impact": 10},
    "visa": {"score": 18, "rating": "Low", "score_impact": 5},
    "mastercard": {"score": 17, "rating": "Low", "score_impact": 5},
    "discover": {"score": 22, "rating": "Medium", "score_impact": 10},
    "capital one": {"score": 25, "rating": "Medium", "score_impact": 10},
    "chase": {"score": 30, "rating": "High", "score_impact": 20},
    "us bank": {"score": 24, "rating": "Medium", "score_impact": 10},
    "pnc": {"score": 22, "rating": "Medium", "score_impact": 10},
    "td bank": {"score": 23, "rating": "Medium", "score_impact": 10},
    "ally bank": {"score": 20, "rating": "Medium", "score_impact": 10},
    "charles schwab": {"score": 18, "rating": "Low", "score_impact": 5},
    "fidelity": {"score": 16, "rating": "Low", "score_impact": 5},
    "vanguard": {"score": 14, "rating": "Low", "score_impact": 5},
    "blackrock": {"score": 26, "rating": "Medium", "score_impact": 10},
    "berkshire hathaway": {"score": 28, "rating": "Medium", "score_impact": 10},
    "coinbase": {"score": 30, "rating": "High", "score_impact": 20},
    "robinhood": {"score": 32, "rating": "High", "score_impact": 20},
    "h&r block": {"score": 20, "rating": "Medium", "score_impact": 10},
    "intuit": {"score": 15, "rating": "Low", "score_impact": 5},
    "stripe": {"score": 14, "rating": "Low", "score_impact": 5},
    "western union": {"score": 28, "rating": "Medium", "score_impact": 10},
    "moneygram": {"score": 30, "rating": "High", "score_impact": 20},

    # --- OIL & ENERGY ---
    "exxon": {"score": 42, "rating": "Severe", "score_impact": 25},
    "exxonmobil": {"score": 42, "rating": "Severe", "score_impact": 25},
    "chevron": {"score": 38, "rating": "High", "score_impact": 20},
    "shell": {"score": 40, "rating": "Severe", "score_impact": 25},
    "bp": {"score": 41, "rating": "Severe", "score_impact": 25},
    "conocophillips": {"score": 36, "rating": "High", "score_impact": 20},
    "marathon oil": {"score": 35, "rating": "High", "score_impact": 20},
    "valero": {"score": 34, "rating": "High", "score_impact": 20},
    "phillips 66": {"score": 33, "rating": "High", "score_impact": 20},
    "halliburton": {"score": 37, "rating": "High", "score_impact": 20},
    "schlumberger": {"score": 35, "rating": "High", "score_impact": 20},
    "duke energy": {"score": 30, "rating": "High", "score_impact": 20},
    "dominion energy": {"score": 29, "rating": "Medium", "score_impact": 10},
    "nextera energy": {"score": 18, "rating": "Low", "score_impact": 5},
    "tesla energy": {"score": 14, "rating": "Low", "score_impact": 5},
    "sunrun": {"score": 15, "rating": "Low", "score_impact": 5},
    "firstsolar": {"score": 13, "rating": "Low", "score_impact": 5},
    "first solar": {"score": 13, "rating": "Low", "score_impact": 5},
    "enphase": {"score": 14, "rating": "Low", "score_impact": 5},
    "american electric power": {"score": 28, "rating": "Medium", "score_impact": 10},

    # --- PHARMACEUTICALS ---
    "johnson and johnson": {"score": 34, "rating": "High", "score_impact": 20},
    "johnson & johnson": {"score": 34, "rating": "High", "score_impact": 20},
    "pfizer": {"score": 28, "rating": "Medium", "score_impact": 10},
    "moderna": {"score": 22, "rating": "Medium", "score_impact": 10},
    "astrazeneca": {"score": 24, "rating": "Medium", "score_impact": 10},
    "merck": {"score": 26, "rating": "Medium", "score_impact": 10},
    "abbvie": {"score": 30, "rating": "High", "score_impact": 20},
    "bristol myers squibb": {"score": 24, "rating": "Medium", "score_impact": 10},
    "eli lilly": {"score": 22, "rating": "Medium", "score_impact": 10},
    "novartis": {"score": 20, "rating": "Medium", "score_impact": 10},
    "roche": {"score": 18, "rating": "Low", "score_impact": 5},
    "sanofi": {"score": 20, "rating": "Medium", "score_impact": 10},
    "glaxosmithkline": {"score": 22, "rating": "Medium", "score_impact": 10},
    "gsk": {"score": 22, "rating": "Medium", "score_impact": 10},
    "bayer": {"score": 36, "rating": "High", "score_impact": 20},
    "mckesson": {"score": 32, "rating": "High", "score_impact": 20},
    "cardinal health": {"score": 30, "rating": "High", "score_impact": 20},
    "cigna": {"score": 26, "rating": "Medium", "score_impact": 10},
    "unitedhealth": {"score": 28, "rating": "Medium", "score_impact": 10},
    "anthem": {"score": 27, "rating": "Medium", "score_impact": 10},
    "humana": {"score": 24, "rating": "Medium", "score_impact": 10},
    "aetna": {"score": 25, "rating": "Medium", "score_impact": 10},
    "purdue pharma": {"score": 50, "rating": "Severe", "score_impact": 25},
    "mallinckrodt": {"score": 48, "rating": "Severe", "score_impact": 25},
    "endo pharmaceuticals": {"score": 46, "rating": "Severe", "score_impact": 25},

    # --- MEDIA & ENTERTAINMENT ---
    "disney": {"score": 20, "rating": "Medium", "score_impact": 10},
    "warner bros": {"score": 24, "rating": "Medium", "score_impact": 10},
    "comcast": {"score": 30, "rating": "High", "score_impact": 20},
    "nbc": {"score": 26, "rating": "Medium", "score_impact": 10},
    "fox": {"score": 32, "rating": "High", "score_impact": 20},
    "fox news": {"score": 35, "rating": "High", "score_impact": 20},
    "cnn": {"score": 26, "rating": "Medium", "score_impact": 10},
    "new york times": {"score": 18, "rating": "Low", "score_impact": 5},
    "buzzfeed": {"score": 22, "rating": "Medium", "score_impact": 10},
    "viacom": {"score": 28, "rating": "Medium", "score_impact": 10},

    # --- FOOD & BEVERAGE ---
    "coca cola": {"score": 33, "rating": "High", "score_impact": 20},
    "pepsi": {"score": 30, "rating": "High", "score_impact": 20},
    "nestle": {"score": 36, "rating": "High", "score_impact": 20},
    "unilever": {"score": 22, "rating": "Medium", "score_impact": 10},
    "kraft heinz": {"score": 32, "rating": "High", "score_impact": 20},
    "general mills": {"score": 26, "rating": "Medium", "score_impact": 10},
    "kelloggs": {"score": 24, "rating": "Medium", "score_impact": 10},
    "conagra": {"score": 28, "rating": "Medium", "score_impact": 10},
    "tyson foods": {"score": 38, "rating": "High", "score_impact": 20},
    "perdue": {"score": 36, "rating": "High", "score_impact": 20},
    "smithfield": {"score": 40, "rating": "Severe", "score_impact": 25},
    "beyond meat": {"score": 14, "rating": "Low", "score_impact": 5},
    "impossible foods": {"score": 13, "rating": "Low", "score_impact": 5},
    "red bull": {"score": 22, "rating": "Medium", "score_impact": 10},
    "monster energy": {"score": 24, "rating": "Medium", "score_impact": 10},
    # --- EDUCATION ---
    "university of phoenix": {"score": 38, "rating": "High", "score_impact": 20},
    "devry university": {"score": 40, "rating": "Severe", "score_impact": 25},
    "strayer university": {"score": 32, "rating": "High", "score_impact": 20},
    "grand canyon university": {"score": 34, "rating": "High", "score_impact": 20},
    "full sail university": {"score": 28, "rating": "Medium", "score_impact": 10},
    "capella university": {"score": 30, "rating": "High", "score_impact": 20},
    "walden university": {"score": 29, "rating": "Medium", "score_impact": 10},
    "liberty university": {"score": 33, "rating": "High", "score_impact": 20},
    "western governors university": {"score": 16, "rating": "Low", "score_impact": 5},
    "wgu": {"score": 16, "rating": "Low", "score_impact": 5},
    "khan academy": {"score": 8, "rating": "Negligible", "score_impact": 0},
    "coursera": {"score": 12, "rating": "Low", "score_impact": 5},
    "udemy": {"score": 14, "rating": "Low", "score_impact": 5},
    "chegg": {"score": 30, "rating": "High", "score_impact": 20},
    "chegg inc": {"score": 30, "rating": "High", "score_impact": 20},
    "pearson": {"score": 26, "rating": "Medium", "score_impact": 10},
    "mcgraw hill": {"score": 25, "rating": "Medium", "score_impact": 10},
    "cengage": {"score": 28, "rating": "Medium", "score_impact": 10},
    "duolingo": {"score": 10, "rating": "Low", "score_impact": 5},
    "skillshare": {"score": 12, "rating": "Low", "score_impact": 5},
    "linkedin learning": {"score": 14, "rating": "Low", "score_impact": 5},
    "masterclass": {"score": 13, "rating": "Low", "score_impact": 5},
    "codecademy": {"score": 11, "rating": "Low", "score_impact": 5},
    "pluralsight": {"score": 13, "rating": "Low", "score_impact": 5},
    "edx": {"score": 10, "rating": "Low", "score_impact": 5},
    "mit opencourseware": {"score": 5, "rating": "Negligible", "score_impact": 0},
    "kaplan": {"score": 24, "rating": "Medium", "score_impact": 10},
    "princeton review": {"score": 20, "rating": "Medium", "score_impact": 10},
    "sylvan learning": {"score": 16, "rating": "Low", "score_impact": 5},
    "kumon": {"score": 14, "rating": "Low", "score_impact": 5},

    # --- AUTOMOTIVE ---
    "tesla": {"score": 30, "rating": "High", "score_impact": 20},
    "ford": {"score": 28, "rating": "Medium", "score_impact": 10},
    "general motors": {"score": 30, "rating": "High", "score_impact": 20},
    "gm": {"score": 30, "rating": "High", "score_impact": 20},
    "chevrolet": {"score": 30, "rating": "High", "score_impact": 20},
    "chrysler": {"score": 32, "rating": "High", "score_impact": 20},
    "dodge": {"score": 32, "rating": "High", "score_impact": 20},
    "jeep": {"score": 32, "rating": "High", "score_impact": 20},
    "stellantis": {"score": 32, "rating": "High", "score_impact": 20},
    "toyota": {"score": 22, "rating": "Medium", "score_impact": 10},
    "honda": {"score": 20, "rating": "Medium", "score_impact": 10},
    "nissan": {"score": 24, "rating": "Medium", "score_impact": 10},
    "hyundai": {"score": 22, "rating": "Medium", "score_impact": 10},
    "kia": {"score": 22, "rating": "Medium", "score_impact": 10},
    "volkswagen": {"score": 35, "rating": "High", "score_impact": 20},
    "vw": {"score": 35, "rating": "High", "score_impact": 20},
    "bmw": {"score": 20, "rating": "Medium", "score_impact": 10},
    "mercedes": {"score": 22, "rating": "Medium", "score_impact": 10},
    "mercedes benz": {"score": 22, "rating": "Medium", "score_impact": 10},
    "audi": {"score": 26, "rating": "Medium", "score_impact": 10},
    "porsche": {"score": 24, "rating": "Medium", "score_impact": 10},
    "volvo": {"score": 16, "rating": "Low", "score_impact": 5},
    "subaru": {"score": 18, "rating": "Low", "score_impact": 5},
    "mazda": {"score": 19, "rating": "Low", "score_impact": 5},
    "rivian": {"score": 14, "rating": "Low", "score_impact": 5},
    "lucid motors": {"score": 13, "rating": "Low", "score_impact": 5},
    "carmax": {"score": 20, "rating": "Medium", "score_impact": 10},
    "carvana": {"score": 32, "rating": "High", "score_impact": 20},
    "autozone": {"score": 22, "rating": "Medium", "score_impact": 10},
    "oreilly auto parts": {"score": 21, "rating": "Medium", "score_impact": 10},

    # --- TRAVEL & HOSPITALITY ---
    "marriott": {"score": 22, "rating": "Medium", "score_impact": 10},
    "hilton": {"score": 20, "rating": "Medium", "score_impact": 10},
    "hyatt": {"score": 18, "rating": "Low", "score_impact": 5},
    "ihg": {"score": 20, "rating": "Medium", "score_impact": 10},
    "wyndham": {"score": 24, "rating": "Medium", "score_impact": 10},
    "best western": {"score": 20, "rating": "Medium", "score_impact": 10},
    "holiday inn": {"score": 20, "rating": "Medium", "score_impact": 10},
    "expedia": {"score": 18, "rating": "Low", "score_impact": 5},
    "booking.com": {"score": 19, "rating": "Low", "score_impact": 5},
    "tripadvisor": {"score": 16, "rating": "Low", "score_impact": 5},
    "delta airlines": {"score": 28, "rating": "Medium", "score_impact": 10},
    "united airlines": {"score": 30, "rating": "High", "score_impact": 20},
    "american airlines": {"score": 32, "rating": "High", "score_impact": 20},
    "southwest airlines": {"score": 24, "rating": "Medium", "score_impact": 10},
    "spirit airlines": {"score": 30, "rating": "High", "score_impact": 20},
    "frontier airlines": {"score": 28, "rating": "Medium", "score_impact": 10},
    "jetblue": {"score": 22, "rating": "Medium", "score_impact": 10},
    "carnival cruise": {"score": 38, "rating": "High", "score_impact": 20},
    "royal caribbean": {"score": 35, "rating": "High", "score_impact": 20},
    "norwegian cruise": {"score": 34, "rating": "High", "score_impact": 20},
    "enterprise": {"score": 20, "rating": "Medium", "score_impact": 10},
    "hertz": {"score": 26, "rating": "Medium", "score_impact": 10},
    "avis": {"score": 22, "rating": "Medium", "score_impact": 10},
    "budget": {"score": 22, "rating": "Medium", "score_impact": 10},

    # --- INSURANCE ---
    "state farm": {"score": 20, "rating": "Medium", "score_impact": 10},
    "allstate": {"score": 24, "rating": "Medium", "score_impact": 10},
    "geico": {"score": 22, "rating": "Medium", "score_impact": 10},
    "progressive": {"score": 20, "rating": "Medium", "score_impact": 10},
    "farmers insurance": {"score": 24, "rating": "Medium", "score_impact": 10},
    "liberty mutual": {"score": 22, "rating": "Medium", "score_impact": 10},
    "usaa": {"score": 16, "rating": "Low", "score_impact": 5},
    "nationwide": {"score": 20, "rating": "Medium", "score_impact": 10},
    "travelers": {"score": 18, "rating": "Low", "score_impact": 5},
    "metlife": {"score": 22, "rating": "Medium", "score_impact": 10},
    "prudential": {"score": 24, "rating": "Medium", "score_impact": 10},
    "new york life": {"score": 18, "rating": "Low", "score_impact": 5},
    "aig": {"score": 32, "rating": "High", "score_impact": 20},
    "aflac": {"score": 16, "rating": "Low", "score_impact": 5},
    "oscar health": {"score": 18, "rating": "Low", "score_impact": 5},

    # --- TELECOM ---
    "att": {"score": 30, "rating": "High", "score_impact": 20},
    "at&t": {"score": 30, "rating": "High", "score_impact": 20},
    "verizon": {"score": 26, "rating": "Medium", "score_impact": 10},
    "tmobile": {"score": 24, "rating": "Medium", "score_impact": 10},
    "t-mobile": {"score": 24, "rating": "Medium", "score_impact": 10},
    "sprint": {"score": 28, "rating": "Medium", "score_impact": 10},
    "xfinity": {"score": 30, "rating": "High", "score_impact": 20},
    "spectrum": {"score": 30, "rating": "High", "score_impact": 20},
    "cox": {"score": 26, "rating": "Medium", "score_impact": 10},
    "dish network": {"score": 28, "rating": "Medium", "score_impact": 10},
    "directv": {"score": 26, "rating": "Medium", "score_impact": 10},
    "cricket wireless": {"score": 22, "rating": "Medium", "score_impact": 10},
    "boost mobile": {"score": 24, "rating": "Medium", "score_impact": 10},
    "metro pcs": {"score": 22, "rating": "Medium", "score_impact": 10},

    # --- LOGISTICS & DELIVERY ---
    "ups": {"score": 22, "rating": "Medium", "score_impact": 10},
    "fedex": {"score": 24, "rating": "Medium", "score_impact": 10},
    "usps": {"score": 18, "rating": "Low", "score_impact": 5},
    "dhl": {"score": 20, "rating": "Medium", "score_impact": 10},
    "doordash": {"score": 28, "rating": "Medium", "score_impact": 10},
    "grubhub": {"score": 26, "rating": "Medium", "score_impact": 10},
    "ubereats": {"score": 28, "rating": "Medium", "score_impact": 10},
    "instacart": {"score": 22, "rating": "Medium", "score_impact": 10},
    "shipt": {"score": 20, "rating": "Medium", "score_impact": 10},
    "postmates": {"score": 24, "rating": "Medium", "score_impact": 10},

    # --- REAL ESTATE ---
    "zillow": {"score": 20, "rating": "Medium", "score_impact": 10},
    "redfin": {"score": 16, "rating": "Low", "score_impact": 5},
    "realtor.com": {"score": 18, "rating": "Low", "score_impact": 5},
    "opendoor": {"score": 22, "rating": "Medium", "score_impact": 10},
    "keller williams": {"score": 18, "rating": "Low", "score_impact": 5},
    "coldwell banker": {"score": 20, "rating": "Medium", "score_impact": 10},
    "remax": {"score": 19, "rating": "Low", "score_impact": 5},
    "century 21": {"score": 20, "rating": "Medium", "score_impact": 10},
    "blackstone": {"score": 34, "rating": "High", "score_impact": 20},
    "invitation homes": {"score": 32, "rating": "High", "score_impact": 20},
    "american homes 4 rent": {"score": 30, "rating": "High", "score_impact": 20},
}

def get_esg_rating(business_name):
    try:
        key = business_name.lower().strip()
        data = ESG_DATA.get(key, None)

        if not data:
            return {"found": False, "esg_score": None, "score_impact": 0}

        return {
            "found": True,
            "esg_score": data["score"],
            "rating": data["rating"],
            "score_impact": data["score_impact"]
        }
    except Exception as e:
        return {"found": False, "esg_score": None, "score_impact": 0}
