# Movement Advancement Project (MAP) — LGBTQ+ State Policy Data
# Source: mapresearch.org/equality-maps
# Tracks 50+ LGBTQ laws and policies per state, scored -31 to +49
# Categories: Relationship & Parental Recognition, Nondiscrimination,
# Religious Exemptions, LGBTQ Youth, Health Care, Criminal Justice, Identity Documents

MAP_DATA = {
    "alabama": {
        "tally_score": -14.5,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ nondiscrimination protections", "Anti-transgender healthcare laws restrict access for minors"],
        "source": "https://mapresearch.org/equality-maps/profile_state/AL"
    },
    "alaska": {
        "tally_score": 3.5,
        "category": "low",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": ["Limited statewide nondiscrimination protections"],
        "source": "https://mapresearch.org/equality-maps/profile_state/AK"
    },
    "arizona": {
        "tally_score": 2.0,
        "category": "low",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination law", "Anti-trans school sports ban in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/AZ"
    },
    "arkansas": {
        "tally_score": -16.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-transgender healthcare ban", "Anti-trans sports ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/AR"
    },
    "california": {
        "tally_score": 44.5,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/CA"
    },
    "colorado": {
        "tally_score": 40.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/CO"
    },
    "connecticut": {
        "tally_score": 41.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/CT"
    },
    "delaware": {
        "tally_score": 35.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/DE"
    },
    "florida": {
        "tally_score": -14.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["HRC travel advisory active", "Don't Say Gay law restricts LGBTQ+ discussion in schools", "Anti-trans healthcare ban for minors", "Anti-drag performance laws"],
        "source": "https://mapresearch.org/equality-maps/profile_state/FL"
    },
    "georgia": {
        "tally_score": -3.5,
        "category": "low",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans sports ban in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/GA"
    },
    "hawaii": {
        "tally_score": 38.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/HI"
    },
    "idaho": {
        "tally_score": -15.5,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans healthcare and sports bans"],
        "source": "https://mapresearch.org/equality-maps/profile_state/ID"
    },
    "illinois": {
        "tally_score": 40.5,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/IL"
    },
    "indiana": {
        "tally_score": -8.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans healthcare ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/IN"
    },
    "iowa": {
        "tally_score": 5.0,
        "category": "low",
        "nondiscrimination": True,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["Anti-trans sports ban in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/IA"
    },
    "kansas": {
        "tally_score": -10.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans laws in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/KS"
    },
    "kentucky": {
        "tally_score": -13.5,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans healthcare and sports bans"],
        "source": "https://mapresearch.org/equality-maps/profile_state/KY"
    },
    "louisiana": {
        "tally_score": -13.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans healthcare ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/LA"
    },
    "maine": {
        "tally_score": 36.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/ME"
    },
    "maryland": {
        "tally_score": 39.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/MD"
    },
    "massachusetts": {
        "tally_score": 43.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/MA"
    },
    "michigan": {
        "tally_score": 28.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/MI"
    },
    "minnesota": {
        "tally_score": 41.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/MN"
    },
    "mississippi": {
        "tally_score": -17.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Broad religious exemption laws permit discrimination", "Anti-trans laws in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/MS"
    },
    "missouri": {
        "tally_score": -11.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans healthcare ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/MO"
    },
    "montana": {
        "tally_score": -12.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans laws in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/MT"
    },
    "nebraska": {
        "tally_score": -10.5,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans healthcare ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/NE"
    },
    "nevada": {
        "tally_score": 32.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/NV"
    },
    "new hampshire": {
        "tally_score": 22.0,
        "category": "medium",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/NH"
    },
    "new jersey": {
        "tally_score": 42.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/NJ"
    },
    "new mexico": {
        "tally_score": 35.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/NM"
    },
    "new york": {
        "tally_score": 43.5,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/NY"
    },
    "north carolina": {
        "tally_score": -2.0,
        "category": "low",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans sports ban in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/NC"
    },
    "north dakota": {
        "tally_score": -14.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans laws in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/ND"
    },
    "ohio": {
        "tally_score": -4.0,
        "category": "low",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans healthcare ban for minors"],
        "source": "https://mapresearch.org/equality-maps/profile_state/OH"
    },
    "oklahoma": {
        "tally_score": -15.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Multiple anti-trans laws in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/OK"
    },
    "oregon": {
        "tally_score": 41.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/OR"
    },
    "pennsylvania": {
        "tally_score": 15.0,
        "category": "medium",
        "nondiscrimination": False,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": ["No statewide employment nondiscrimination law"],
        "source": "https://mapresearch.org/equality-maps/profile_state/PA"
    },
    "rhode island": {
        "tally_score": 39.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/RI"
    },
    "south carolina": {
        "tally_score": -9.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans sports ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/SC"
    },
    "south dakota": {
        "tally_score": -14.5,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans healthcare and sports bans"],
        "source": "https://mapresearch.org/equality-maps/profile_state/SD"
    },
    "tennessee": {
        "tally_score": -18.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-drag performance laws", "Anti-trans healthcare ban", "Anti-trans sports ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/TN"
    },
    "texas": {
        "tally_score": -15.5,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": True,
        "advisories": ["No statewide nondiscrimination protections", "Anti-trans healthcare ban", "Criminalization of gender-affirming care for minors"],
        "source": "https://mapresearch.org/equality-maps/profile_state/TX"
    },
    "utah": {
        "tally_score": -5.0,
        "category": "low",
        "nondiscrimination": True,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["Anti-trans healthcare and sports bans in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/UT"
    },
    "vermont": {
        "tally_score": 44.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/VT"
    },
    "virginia": {
        "tally_score": 28.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/VA"
    },
    "washington": {
        "tally_score": 42.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/WA"
    },
    "washington dc": {
        "tally_score": 45.0,
        "category": "high",
        "nondiscrimination": True,
        "conversion_therapy_ban": True,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": True,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": [],
        "source": "https://mapresearch.org/equality-maps/profile_state/DC"
    },
    "west virginia": {
        "tally_score": -11.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans healthcare ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/WV"
    },
    "wisconsin": {
        "tally_score": 8.0,
        "category": "low",
        "nondiscrimination": True,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": True,
        "healthcare_protections": False,
        "hate_crimes": True,
        "anti_trans_laws": False,
        "advisories": ["Limited protections — no conversion therapy ban"],
        "source": "https://mapresearch.org/equality-maps/profile_state/WI"
    },
    "wyoming": {
        "tally_score": -8.0,
        "category": "negative",
        "nondiscrimination": False,
        "conversion_therapy_ban": False,
        "same_sex_marriage": True,
        "adoption_equality": False,
        "healthcare_protections": False,
        "hate_crimes": False,
        "anti_trans_laws": True,
        "advisories": ["No statewide LGBTQ+ protections", "Anti-trans laws in effect"],
        "source": "https://mapresearch.org/equality-maps/profile_state/WY"
    }
}

def get_map_data(state_name):
    """Get MAP LGBTQ+ policy data for a state"""
    key = state_name.lower().strip()
    if key in MAP_DATA:
        return {"found": True, **MAP_DATA[key]}
    for state, data in MAP_DATA.items():
        if state in key or key in state:
            return {"found": True, **data}
    return {"found": False}

def get_map_lgbtq_rating(state_name):
    """Convert MAP tally score to our rating system"""
    data = get_map_data(state_name)
    if not data["found"]:
        return None
    score = data["tally_score"]
    if score >= 25:
        return "Low Risk"
    elif score >= 5:
        return "Medium Risk"
    elif score >= -5:
        return "Medium Risk"
    else:
        return "High Risk"
