# Product-to-company mapping
# Sources: Open Food Facts, company annual reports, brand ownership databases
# Maps consumer product names to their parent companies

PRODUCT_MAP = {
    # MONDELEZ INTERNATIONAL
    "oreos": "Mondelez International",
    "oreo": "Mondelez International",
    "chips ahoy": "Mondelez International",
    "ritz crackers": "Mondelez International",
    "ritz": "Mondelez International",
    "wheat thins": "Mondelez International",
    "triscuit": "Mondelez International",
    "triscuits": "Mondelez International",
    "cadbury": "Mondelez International",
    "toblerone": "Mondelez International",
    "sour patch kids": "Mondelez International",
    "swedish fish": "Mondelez International",
    "halls": "Mondelez International",
    "nabisco": "Mondelez International",
    "honey maid": "Mondelez International",
    "newtons": "Mondelez International",
    "fig newtons": "Mondelez International",
    "nutter butter": "Mondelez International",
    "belVita": "Mondelez International",
    "belvita": "Mondelez International",
    "milka": "Mondelez International",
    "dentyne": "Mondelez International",
    "stride gum": "Mondelez International",
    "trident": "Mondelez International",
    "bubblicious": "Mondelez International",
    "premium crackers": "Mondelez International",

    # NESTLE
    "kit kat": "Nestle",
    "kitkat": "Nestle",
    "nesquik": "Nestle",
    "nescafe": "Nestle",
    "coffee mate": "Nestle",
    "coffeemate": "Nestle",
    "lean cuisine": "Nestle",
    "stouffers": "Nestle",
    "stouffer's": "Nestle",
    "hot pockets": "Nestle",
    "digiorno": "Nestle",
    "tombstone pizza": "Nestle",
    "jack's pizza": "Nestle",
    "california pizza kitchen frozen": "Nestle",
    "perrier": "Nestle",
    "san pellegrino": "Nestle",
    "poland spring": "Nestle",
    "deer park water": "Nestle",
    "pure life": "Nestle",
    "gerber": "Nestle",
    "purina": "Nestle",
    "purina pro plan": "Nestle",
    "purina one": "Nestle",
    "fancy feast": "Nestle",
    "friskies": "Nestle",
    "alpo": "Nestle",
    "beneful": "Nestle",
    "dog chow": "Nestle",
    "cat chow": "Nestle",
    "meow mix": "Nestle",
    "milo": "Nestle",
    "maggi": "Nestle",
    "haagen dazs": "Nestle",
    "häagen-dazs": "Nestle",
    "drumstick ice cream": "Nestle",
    "butterfinger": "Nestle",
    "baby ruth": "Nestle",
    "crunch bar": "Nestle",
    "wonka candy": "Nestle",

    # PROCTER & GAMBLE
    "tide": "Procter & Gamble",
    "tide pods": "Procter & Gamble",
    "ariel": "Procter & Gamble",
    "downy": "Procter & Gamble",
    "bounce dryer sheets": "Procter & Gamble",
    "cascade": "Procter & Gamble",
    "dawn dish soap": "Procter & Gamble",
    "dawn": "Procter & Gamble",
    "mr clean": "Procter & Gamble",
    "mr. clean": "Procter & Gamble",
    "swiffer": "Procter & Gamble",
    "febreze": "Procter & Gamble",
    "pampers": "Procter & Gamble",
    "luvs diapers": "Procter & Gamble",
    "always": "Procter & Gamble",
    "tampax": "Procter & Gamble",
    "charmin": "Procter & Gamble",
    "bounty paper towels": "Procter & Gamble",
    "bounty": "Procter & Gamble",
    "puffs tissues": "Procter & Gamble",
    "gillette": "Procter & Gamble",
    "venus razor": "Procter & Gamble",
    "venus": "Procter & Gamble",
    "braun": "Procter & Gamble",
    "oral b": "Procter & Gamble",
    "oral-b": "Procter & Gamble",
    "crest": "Procter & Gamble",
    "scope mouthwash": "Procter & Gamble",
    "head and shoulders": "Procter & Gamble",
    "head & shoulders": "Procter & Gamble",
    "pantene": "Procter & Gamble",
    "herbal essences": "Procter & Gamble",
    "aussie shampoo": "Procter & Gamble",
    "old spice": "Procter & Gamble",
    "secret deodorant": "Procter & Gamble",
    "secret": "Procter & Gamble",
    "olay": "Procter & Gamble",
    "olay regenerist": "Procter & Gamble",
    "sk-ii": "Procter & Gamble",
    "vicks": "Procter & Gamble",
    "nyquil": "Procter & Gamble",
    "dayquil": "Procter & Gamble",
    "pepto bismol": "Procter & Gamble",
    "metamucil": "Procter & Gamble",
    "prilosec otc": "Procter & Gamble",

    # UNILEVER
    "dove soap": "Unilever",
    "dove": "Unilever",
    "axe body spray": "Unilever",
    "axe": "Unilever",
    "degree deodorant": "Unilever",
    "degree": "Unilever",
    "suave": "Unilever",
    "tresemme": "Unilever",
    "tresemmé": "Unilever",
    "vaseline": "Unilever",
    "ponds": "Unilever",
    "pond's": "Unilever",
    "st ives": "Unilever",
    "st. ives": "Unilever",
    "simple skincare": "Unilever",
    "caress": "Unilever",
    "lux soap": "Unilever",
    "lifebuoy": "Unilever",
    "signal toothpaste": "Unilever",
    "closeup toothpaste": "Unilever",
    "comfort fabric softener": "Unilever",
    "surf detergent": "Unilever",
    "omo detergent": "Unilever",
    "domestos": "Unilever",
    "cif cleaner": "Unilever",
    "hellmanns": "Unilever",
    "hellmann's": "Unilever",
    "best foods mayo": "Unilever",
    "knorr": "Unilever",
    "lipton tea": "Unilever",
    "lipton": "Unilever",
    "pure leaf tea": "Unilever",
    "brisk tea": "Unilever",
    "ben and jerrys": "Unilever",
    "ben & jerry's": "Unilever",
    "breyers": "Unilever",
    "talenti gelato": "Unilever",
    "magnum ice cream": "Unilever",
    "popsicle": "Unilever",
    "good humor": "Unilever",
    "klondike": "Unilever",
    "slim fast": "Unilever",

    # COCA-COLA
    "coca cola": "Coca-Cola",
    "coke": "Coca-Cola",
    "diet coke": "Coca-Cola",
    "coke zero": "Coca-Cola",
    "sprite": "Coca-Cola",
    "fanta": "Coca-Cola",
    "minute maid": "Coca-Cola",
    "simply orange": "Coca-Cola",
    "dasani water": "Coca-Cola",
    "dasani": "Coca-Cola",
    "smartwater": "Coca-Cola",
    "vitaminwater": "Coca-Cola",
    "vitamin water": "Coca-Cola",
    "powerade": "Coca-Cola",
    "honest tea": "Coca-Cola",
    "fairlife milk": "Coca-Cola",
    "fairlife": "Coca-Cola",
    "barqs root beer": "Coca-Cola",
    "pibb xtra": "Coca-Cola",
    "mello yello": "Coca-Cola",
    "fresca": "Coca-Cola",
    "schweppes": "Coca-Cola",
    "aha sparkling water": "Coca-Cola",
    "topo chico": "Coca-Cola",
    "monster energy": "Coca-Cola",
    "georgia coffee": "Coca-Cola",

    # PEPSICO
    "pepsi": "PepsiCo",
    "mountain dew": "PepsiCo",
    "mtn dew": "PepsiCo",
    "gatorade": "PepsiCo",
    "tropicana": "PepsiCo",
    "lipton brisk": "PepsiCo",
    "aquafina": "PepsiCo",
    "lays chips": "PepsiCo",
    "lay's": "PepsiCo",
    "doritos": "PepsiCo",
    "cheetos": "PepsiCo",
    "fritos": "PepsiCo",
    "ruffles": "PepsiCo",
    "tostitos": "PepsiCo",
    "sunchips": "PepsiCo",
    "smartfood popcorn": "PepsiCo",
    "cracker jack": "PepsiCo",
    "quaker oats": "PepsiCo",
    "quaker": "PepsiCo",
    "life cereal": "PepsiCo",
    "cap n crunch": "PepsiCo",
    "cap'n crunch": "PepsiCo",
    "rice a roni": "PepsiCo",
    "near east": "PepsiCo",
    "pasta roni": "PepsiCo",
    "stacy's pita chips": "PepsiCo",
    "off the eaten path": "PepsiCo",
    "bare snacks": "PepsiCo",
    "pepsi max": "PepsiCo",
    "sierra mist": "PepsiCo",
    "7up": "PepsiCo",
    "dr pepper": "PepsiCo",
    "lipton green tea pepsi": "PepsiCo",
    "naked juice": "PepsiCo",
    "kevita": "PepsiCo",
    "bubly sparkling water": "PepsiCo",

    # KRAFT HEINZ
    "heinz ketchup": "Kraft Heinz",
    "heinz": "Kraft Heinz",
    "kraft mac and cheese": "Kraft Heinz",
    "kraft": "Kraft Heinz",
    "oscar mayer": "Kraft Heinz",
    "lunchables": "Kraft Heinz",
    "philadelphia cream cheese": "Kraft Heinz",
    "philadelphia": "Kraft Heinz",
    "velveeta": "Kraft Heinz",
    "jell-o": "Kraft Heinz",
    "jello": "Kraft Heinz",
    "cool whip": "Kraft Heinz",
    "kool aid": "Kraft Heinz",
    "kool-aid": "Kraft Heinz",
    "capri sun": "Kraft Heinz",
    "classico pasta sauce": "Kraft Heinz",
    "grey poupon": "Kraft Heinz",
    "a1 steak sauce": "Kraft Heinz",
    "a.1.": "Kraft Heinz",
    "planters peanuts": "Kraft Heinz",
    "planters": "Kraft Heinz",
    "mr peanut": "Kraft Heinz",
    "bagel bites": "Kraft Heinz",
    "ore-ida": "Kraft Heinz",
    "stove top stuffing": "Kraft Heinz",
    "country time lemonade": "Kraft Heinz",
    "tang": "Kraft Heinz",
    "maxwell house coffee": "Kraft Heinz",
    "maxwell house": "Kraft Heinz",
    "gevalia coffee": "Kraft Heinz",

    # GENERAL MILLS
    "cheerios": "General Mills",
    "lucky charms": "General Mills",
    "cocoa puffs": "General Mills",
    "trix cereal": "General Mills",
    "wheaties": "General Mills",
    "total cereal": "General Mills",
    "kix cereal": "General Mills",
    "fiber one": "General Mills",
    "nature valley": "General Mills",
    "larabar": "General Mills",
    "yoplait": "General Mills",
    "pillsbury": "General Mills",
    "grand biscuits": "General Mills",
    "pillsbury grands": "General Mills",
    "bisquick": "General Mills",
    "betty crocker": "General Mills",
    "hamburger helper": "General Mills",
    "progresso soup": "General Mills",
    "progresso": "General Mills",
    "green giant": "General Mills",
    "old el paso": "General Mills",
    "annie's": "General Mills",
    "annies": "General Mills",
    "epic provisions": "General Mills",
    "cascadian farm": "General Mills",
    "muir glen": "General Mills",
    "haagen dazs": "General Mills",

    # KELLOGGS
    "frosted flakes": "Kellogg's",
    "froot loops": "Kellogg's",
    "corn flakes": "Kellogg's",
    "special k": "Kellogg's",
    "raisin bran": "Kellogg's",
    "rice krispies": "Kellogg's",
    "pop tarts": "Kellogg's",
    "eggo waffles": "Kellogg's",
    "eggo": "Kellogg's",
    "nutri grain": "Kellogg's",
    "nutri-grain": "Kellogg's",
    "cheez its": "Kellogg's",
    "cheez-it": "Kellogg's",
    "club crackers": "Kellogg's",
    "townhouse crackers": "Kellogg's",
    "pringles": "Kellogg's",
    "krave cereal": "Kellogg's",
    "morningstar farms": "Kellogg's",
    "gardenburger": "Kellogg's",
    "kashi": "Kellogg's",
    "bear naked": "Kellogg's",
    "rxbar": "Kellogg's",

    # CONAGRA
    "birds eye": "Conagra",
    "marie callenders": "Conagra",
    "marie callender's": "Conagra",
    "healthy choice": "Conagra",
    "slim jim": "Conagra",
    "act ii popcorn": "Conagra",
    "orville redenbachers": "Conagra",
    "orville redenbacher's": "Conagra",
    "reddi whip": "Conagra",
    "hunt's tomatoes": "Conagra",
    "hunts": "Conagra",
    "vlasic pickles": "Conagra",
    "vlasic": "Conagra",
    "rotel": "Conagra",
    "pam cooking spray": "Conagra",
    "pam": "Conagra",
    "swiss miss": "Conagra",
    "peter pan peanut butter": "Conagra",
    "snyder's of hanover": "Conagra",
    "snyders": "Conagra",
    "lance crackers": "Conagra",
    "kettle brand": "Conagra",
    "cape cod chips": "Conagra",
    "david sunflower seeds": "Conagra",
    "gardein": "Conagra",
    "bertolli pasta sauce": "Conagra",
    "ranch style beans": "Conagra",

    # CAMPBELL SOUP
    "campbells soup": "Campbell Soup",
    "campbell's": "Campbell Soup",
    "chunky soup": "Campbell Soup",
    "swanson broth": "Campbell Soup",
    "swanson": "Campbell Soup",
    "v8 juice": "Campbell Soup",
    "v8": "Campbell Soup",
    "pepperidge farm": "Campbell Soup",
    "goldfish crackers": "Campbell Soup",
    "goldfish": "Campbell Soup",
    "prego pasta sauce": "Campbell Soup",
    "prego": "Campbell Soup",
    "pace salsa": "Campbell Soup",
    "pace": "Campbell Soup",
    "campbell's chunky": "Campbell Soup",

    # HORMEL
    "spam": "Hormel",
    "skippy peanut butter": "Hormel",
    "skippy": "Hormel",
    "jennie-o turkey": "Hormel",
    "jennie o": "Hormel",
    "applegate farms": "Hormel",
    "applegate": "Hormel",
    "natural choice": "Hormel",
    "dinty moore": "Hormel",
    "hormel chili": "Hormel",
    "lloyd's bbq": "Hormel",
    "house of tsang": "Hormel",
    "wholly guacamole": "Hormel",

    # JOHNSON & JOHNSON (Consumer)
    "tylenol": "Johnson & Johnson",
    "advil": "Johnson & Johnson",
    "motrin": "Johnson & Johnson",
    "benadryl": "Johnson & Johnson",
    "zyrtec": "Johnson & Johnson",
    "band-aid": "Johnson & Johnson",
    "band aid": "Johnson & Johnson",
    "neosporin": "Johnson & Johnson",
    "listerine": "Johnson & Johnson",
    "neutrogena": "Johnson & Johnson",
    "aveeno": "Johnson & Johnson",
    "clean and clear": "Johnson & Johnson",
    "clean & clear": "Johnson & Johnson",
    "johnsons baby": "Johnson & Johnson",
    "johnson's baby": "Johnson & Johnson",
    "desitin": "Johnson & Johnson",
    "rogaine": "Johnson & Johnson",
    "visine": "Johnson & Johnson",
    "sudafed": "Johnson & Johnson",
    "rolaids": "Johnson & Johnson",
    "pepcid": "Johnson & Johnson",
    "imodium": "Johnson & Johnson",
    "splenda": "Johnson & Johnson",

    # COLGATE-PALMOLIVE
    "colgate toothpaste": "Colgate-Palmolive",
    "colgate": "Colgate-Palmolive",
    "palmolive dish soap": "Colgate-Palmolive",
    "palmolive": "Colgate-Palmolive",
    "ajax cleaner": "Colgate-Palmolive",
    "ajax": "Colgate-Palmolive",
    "speed stick": "Colgate-Palmolive",
    "irish spring": "Colgate-Palmolive",
    "softsoap": "Colgate-Palmolive",
    "tom's of maine": "Colgate-Palmolive",
    "toms of maine": "Colgate-Palmolive",
    "hill's science diet": "Colgate-Palmolive",
    "hills science diet": "Colgate-Palmolive",
    "prescription diet": "Colgate-Palmolive",

    # CHURCH & DWIGHT
    "arm and hammer": "Church & Dwight",
    "arm & hammer": "Church & Dwight",
    "oxiclean": "Church & Dwight",
    "oxi clean": "Church & Dwight",
    "trojan condoms": "Church & Dwight",
    "trojan": "Church & Dwight",
    "vitafusion gummies": "Church & Dwight",
    "l'il critters": "Church & Dwight",
    "lil critters": "Church & Dwight",
    "waterpik": "Church & Dwight",
    "spinbrush": "Church & Dwight",
    "nair": "Church & Dwight",
    "batiste dry shampoo": "Church & Dwight",
    "xtra detergent": "Church & Dwight",
    "kaboom cleaner": "Church & Dwight",
    "scrubbing bubbles": "Church & Dwight",

    # SC JOHNSON
    "windex": "SC Johnson",
    "pledge furniture polish": "SC Johnson",
    "pledge": "SC Johnson",
    "raid bug spray": "SC Johnson",
    "raid": "SC Johnson",
    "off bug spray": "SC Johnson",
    "off!": "SC Johnson",
    "ziploc": "SC Johnson",
    "saran wrap": "SC Johnson",
    "glade air freshener": "SC Johnson",
    "glade": "SC Johnson",
    "edge shaving gel": "SC Johnson",
    "skintimate": "SC Johnson",
    "shout stain remover": "SC Johnson",
    "shout": "SC Johnson",
    "drano": "SC Johnson",
    "fantastic cleaner": "SC Johnson",

    # RECKITT
    "lysol": "Reckitt",
    "lysol disinfectant": "Reckitt",
    "woolite": "Reckitt",
    "finish dishwasher": "Reckitt",
    "finish": "Reckitt",
    "mucinex": "Reckitt",
    "delsym": "Reckitt",
    "zarbees": "Reckitt",
    "durex": "Reckitt",
    "clearasil": "Reckitt",
    "veet": "Reckitt",
    "scholl": "Reckitt",
    "calgon": "Reckitt",
    "air wick": "Reckitt",
    "french's mustard": "Reckitt",
    "frank's redhot": "Reckitt",
    "franks red hot": "Reckitt",
    "old english furniture": "Reckitt",

    # HENKEL
    "persil detergent": "Henkel",
    "persil": "Henkel",
    "all detergent": "Henkel",
    "purex detergent": "Henkel",
    "purex": "Henkel",
    "dial soap": "Henkel",
    "dial": "Henkel",
    "right guard": "Henkel",
    "got2b": "Henkel",
    "schwarzkopf": "Henkel",
    "loctite": "Henkel",
    "gorilla glue": "Henkel",
    "super glue": "Henkel",

    # APPLE PRODUCTS
    "iphone": "Apple",
    "ipad": "Apple",
    "macbook": "Apple",
    "mac pro": "Apple",
    "apple watch": "Apple",
    "airpods": "Apple",
    "apple tv": "Apple",
    "imac": "Apple",
    "apple music": "Apple",
    "icloud": "Apple",
    "apple pay": "Apple",
    "siri": "Apple",
    "ios": "Apple",
    "macos": "Apple",
    "app store": "Apple",
    "apple arcade": "Apple",

    # GOOGLE / ALPHABET PRODUCTS
    "google search": "Google",
    "gmail": "Google",
    "google maps": "Google",
    "google drive": "Google",
    "google docs": "Google",
    "google chrome": "Google",
    "android": "Google",
    "pixel phone": "Google",
    "google pixel": "Google",
    "youtube": "Google",
    "google home": "Google",
    "nest thermostat": "Google",
    "nest": "Google",
    "google workspace": "Google",
    "google one": "Google",
    "waymo": "Google",
    "google cloud": "Google",
    "google photos": "Google",
    "google translate": "Google",

    # MICROSOFT PRODUCTS
    "windows": "Microsoft",
    "xbox": "Microsoft",
    "microsoft office": "Microsoft",
    "microsoft 365": "Microsoft",
    "outlook email": "Microsoft",
    "teams": "Microsoft",
    "microsoft teams": "Microsoft",
    "azure": "Microsoft",
    "bing": "Microsoft",
    "linkedin": "Microsoft",
    "github": "Microsoft",
    "skype": "Microsoft",
    "one drive": "Microsoft",
    "onedrive": "Microsoft",
    "surface laptop": "Microsoft",
    "microsoft surface": "Microsoft",
    "copilot": "Microsoft",

    # META PRODUCTS
    "facebook": "Meta",
    "instagram": "Meta",
    "whatsapp": "Meta",
    "messenger": "Meta",
    "oculus": "Meta",
    "meta quest": "Meta",
    "threads": "Meta",
    "workplace by meta": "Meta",

    # AMAZON PRODUCTS
    "amazon prime": "Amazon",
    "amazon alexa": "Amazon",
    "alexa": "Amazon",
    "amazon echo": "Amazon",
    "echo dot": "Amazon",
    "kindle": "Amazon",
    "amazon fresh": "Amazon",
    "amazon basics": "Amazon",
    "amazon music": "Amazon",
    "amazon video": "Amazon",
    "prime video": "Amazon",
    "aws": "Amazon",
    "amazon web services": "Amazon",
    "ring doorbell": "Amazon",
    "ring camera": "Amazon",
    "ring": "Amazon",
    "whole foods": "Amazon",
    "zappos": "Amazon",
    "twitch": "Amazon",
    "audible": "Amazon",
    "goodreads": "Amazon",
    "imdb": "Amazon",

    # DISNEY PRODUCTS / BRANDS
    "disney plus": "Disney",
    "disney+": "Disney",
    "hulu": "Disney",
    "espn": "Disney",
    "espn plus": "Disney",
    "star wars": "Disney",
    "marvel": "Disney",
    "pixar": "Disney",
    "national geographic": "Disney",
    "abc network": "Disney",
    "21st century fox": "Disney",
    "searchlight pictures": "Disney",
    "touchstone pictures": "Disney",
    "freeform": "Disney",
    "fx channel": "Disney",

    # COMCAST / NBCUNIVERSAL
    "xfinity": "Comcast",
    "peacock streaming": "Comcast",
    "nbc": "Comcast",
    "msnbc": "Comcast",
    "cnbc": "Comcast",
    "universal pictures": "Comcast",
    "dreamworks": "Comcast",
    "sky tv": "Comcast",
    "telemundo": "Comcast",

    # WARNER BROS DISCOVERY
    "hbo": "Warner Bros Discovery",
    "max streaming": "Warner Bros Discovery",
    "cnn": "Warner Bros Discovery",
    "tnt channel": "Warner Bros Discovery",
    "tbs channel": "Warner Bros Discovery",
    "cartoon network": "Warner Bros Discovery",
    "discovery channel": "Warner Bros Discovery",
    "tlc channel": "Warner Bros Discovery",
    "animal planet": "Warner Bros Discovery",
    "food network": "Warner Bros Discovery",
    "hgtv": "Warner Bros Discovery",
    "travel channel": "Warner Bros Discovery",
    "dc comics": "Warner Bros Discovery",

    # VOLKSWAGEN GROUP
    "volkswagen": "Volkswagen",
    "audi": "Volkswagen",
    "porsche": "Volkswagen",
    "lamborghini": "Volkswagen",
    "bentley": "Volkswagen",
    "bugatti": "Volkswagen",
    "skoda": "Volkswagen",
    "seat car": "Volkswagen",
    "ducati": "Volkswagen",
    "man trucks": "Volkswagen",

    # STELLANTIS
    "jeep": "Stellantis",
    "dodge": "Stellantis",
    "ram trucks": "Stellantis",
    "chrysler": "Stellantis",
    "fiat": "Stellantis",
    "alfa romeo": "Stellantis",
    "maserati": "Stellantis",
    "peugeot": "Stellantis",
    "citroen": "Stellantis",
    "opel": "Stellantis",

    # JOHNSON & JOHNSON PHARMA
    "janssen pharmaceuticals": "Johnson & Johnson",
    "remicade": "Johnson & Johnson",
    "stelara": "Johnson & Johnson",
    "zytiga": "Johnson & Johnson",
    "imbruvica": "Johnson & Johnson",

    # PFIZER PRODUCTS
    "lipitor": "Pfizer",
    "viagra": "Pfizer",
    "lyrica": "Pfizer",
    "xeljanz": "Pfizer",
    "ibrance": "Pfizer",
    "eliquis": "Pfizer",
    "prevnar": "Pfizer",
    "paxlovid": "Pfizer",
    "comirnaty": "Pfizer",
    "pfizer covid vaccine": "Pfizer",

    # ABBVIE
    "humira": "AbbVie",
    "skyrizi": "AbbVie",
    "rinvoq": "AbbVie",
    "botox": "AbbVie",
    "juvederm": "AbbVie",
    "allergan": "AbbVie",
    "ozurdex": "AbbVie",

    # ELI LILLY
    "ozempic": "Eli Lilly",
    "mounjaro": "Eli Lilly",
    "zepbound": "Eli Lilly",
    "trulicity": "Eli Lilly",
    "humalog insulin": "Eli Lilly",
    "basaglar": "Eli Lilly",
    "taltz": "Eli Lilly",
    "verzenio": "Eli Lilly",
    "cymbalta": "Eli Lilly",

    # NOVO NORDISK
    "wegovy": "Novo Nordisk",
    "ozempic": "Novo Nordisk",
    "victoza": "Novo Nordisk",
    "saxenda": "Novo Nordisk",
    "novolog insulin": "Novo Nordisk",
    "levemir": "Novo Nordisk",

    # EXXON BRANDS
    "exxon gas": "Exxon",
    "mobil gas": "Exxon",
    "esso": "Exxon",
    "synergy fuel": "Exxon",
    "mobil 1 oil": "Exxon",
    "mobil 1": "Exxon",

    # CHEVRON BRANDS
    "chevron gas": "Chevron",
    "texaco": "Chevron",
    "caltex": "Chevron",
    "havoline motor oil": "Chevron",

    # SHELL BRANDS
    "shell gas": "Shell",
    "shell v-power": "Shell",
    "pennzoil": "Shell",
    "quaker state oil": "Shell",

    # BP BRANDS
    "bp gas": "BP",
    "ampm": "BP",
    "arco gas": "BP",
    "castrol oil": "BP",

    # FINANCIAL PRODUCTS
    "chase sapphire": "JPMorgan",
    "chase freedom": "JPMorgan",
    "amazon credit card": "JPMorgan",
    "southwest credit card": "JPMorgan",
    "bank of america credit card": "Bank of America",
    "wells fargo credit card": "Wells Fargo",
    "citi credit card": "Citibank",
    "american express gold": "American Express",
    "amex platinum": "American Express",
    "amex gold": "American Express",
    "discover card": "Discover",
    "capital one venture": "Capital One",
    "capital one quicksilver": "Capital One",

    # ATHLETIC / SPORTS BRANDS
    "nike air max": "Nike",
    "air jordan": "Nike",
    "jordan brand": "Nike",
    "converse": "Nike",
    "hurley": "Nike",
    "adidas ultraboost": "Adidas",
    "yeezy": "Adidas",
    "reebok": "Adidas",
    "under armour shoes": "Under Armour",
    "puma": "Puma",
    "new balance": "New Balance",
    "vans shoes": "VF Corporation",
    "vans": "VF Corporation",
    "north face": "VF Corporation",
    "the north face": "VF Corporation",
    "timberland": "VF Corporation",
    "wrangler jeans": "VF Corporation",
    "lee jeans": "VF Corporation",
    "dickies": "VF Corporation",

    # LEVI STRAUSS
    "levis": "Levi Strauss",
    "levi's jeans": "Levi Strauss",
    "dockers pants": "Levi Strauss",

    # PVH CORP
    "calvin klein": "PVH Corp",
    "tommy hilfiger": "PVH Corp",
    "izod": "PVH Corp",

    # TAPESTRY
    "coach handbags": "Tapestry",
    "coach": "Tapestry",
    "kate spade": "Tapestry",
    "stuart weitzman": "Tapestry",

    # CAPRI HOLDINGS
    "michael kors": "Capri Holdings",
    "versace": "Capri Holdings",
    "jimmy choo": "Capri Holdings",

    # LVMH
    "louis vuitton": "LVMH",
    "dior": "LVMH",
    "givenchy": "LVMH",
    "fendi": "LVMH",
    "marc jacobs": "LVMH",
    "sephora": "LVMH",
    "bulgari": "LVMH",
    "tag heuer": "LVMH",
    "moet hennessy": "LVMH",
    "dom perignon": "LVMH",
    "hennessy cognac": "LVMH",

    # ESTEE LAUDER
    "estee lauder": "Estee Lauder",
    "mac cosmetics": "Estee Lauder",
    "mac makeup": "Estee Lauder",
    "clinique": "Estee Lauder",
    "bobbi brown": "Estee Lauder",
    "too faced": "Estee Lauder",
    "origins skincare": "Estee Lauder",
    "aveda": "Estee Lauder",
    "bumble and bumble": "Estee Lauder",
    "la mer": "Estee Lauder",
    "jo malone": "Estee Lauder",
    "tom ford beauty": "Estee Lauder",

    # REVLON
    "revlon makeup": "Revlon",
    "elizabeth arden": "Revlon",
    "almay": "Revlon",
    "american crew": "Revlon",

    # COTY
    "covergirl": "Coty",
    "rimmel london": "Coty",
    "clairol": "Coty",
    "wella hair": "Coty",
    "ghd hair": "Coty",
    "calvin klein fragrance": "Coty",
    "hugo boss fragrance": "Coty",
    "gucci fragrance": "Coty",
    "burberry fragrance": "Coty",

    # ANHEUSER-BUSCH INBEV
    "budweiser": "Anheuser-Busch",
    "bud light": "Anheuser-Busch",
    "bud light seltzer": "Anheuser-Busch",
    "stella artois": "Anheuser-Busch",
    "corona beer": "Anheuser-Busch",
    "modelo": "Anheuser-Busch",
    "beck's beer": "Anheuser-Busch",
    "hoegaarden": "Anheuser-Busch",
    "leffe": "Anheuser-Busch",
    "michelob ultra": "Anheuser-Busch",
    "natural light": "Anheuser-Busch",
    "busch beer": "Anheuser-Busch",
    "rolling rock": "Anheuser-Busch",
    "shock top": "Anheuser-Busch",
    "goose island": "Anheuser-Busch",

    # MOLSON COORS
    "coors light": "Molson Coors",
    "miller lite": "Molson Coors",
    "miller high life": "Molson Coors",
    "blue moon beer": "Molson Coors",
    "leinenkugels": "Molson Coors",
    "keystone light": "Molson Coors",
    "fosters beer": "Molson Coors",
    "topo chico hard seltzer": "Molson Coors",
    "vizzy hard seltzer": "Molson Coors",

    # CONSTELLATION BRANDS
    "corona extra": "Constellation Brands",
    "modelo especial": "Constellation Brands",
    "pacifico beer": "Constellation Brands",
    "robert mondavi wine": "Constellation Brands",
    "kim crawford wine": "Constellation Brands",
    "meiomi wine": "Constellation Brands",
    "the prisoner wine": "Constellation Brands",
    "svedka vodka": "Constellation Brands",
    "high west whiskey": "Constellation Brands",

    # PHILIP MORRIS / ALTRIA
    "marlboro": "Philip Morris",
    "parliament cigarettes": "Philip Morris",
    "camel cigarettes": "Philip Morris",
    "newport cigarettes": "Philip Morris",
    "juul": "Altria",
    "on! nicotine pouches": "Altria",
    "copenhagen chew": "Altria",
    "skoal": "Altria",

    # TYSON FOODS
    "tyson chicken": "Tyson Foods",
    "jimmy dean": "Tyson Foods",
    "ball park franks": "Tyson Foods",
    "hillshire farm": "Tyson Foods",
    "state fair corn dogs": "Tyson Foods",
    "aidells sausage": "Tyson Foods",
    "wright brand bacon": "Tyson Foods",
    "sara lee deli": "Tyson Foods",

    # SMITHFIELD FOODS
    "smithfield bacon": "Smithfield",
    "eckrich sausage": "Smithfield",
    "farmland foods": "Smithfield",
    "john morrell": "Smithfield",
    "nathans famous": "Smithfield",
    "nathan's famous": "Smithfield",

    # INSURANCE PRODUCTS
    "state farm insurance": "State Farm",
    "geico insurance": "Geico",
    "progressive insurance": "Progressive",
    "allstate insurance": "Allstate",
    "liberty mutual insurance": "Liberty Mutual",
    "nationwide insurance": "Nationwide",
    "usaa insurance": "USAA",
    "aflac duck": "Aflac",
    "aflac insurance": "Aflac",

    # HOTEL BRANDS
    "marriott hotels": "Marriott",
    "sheraton": "Marriott",
    "westin hotels": "Marriott",
    "w hotels": "Marriott",
    "ritz carlton": "Marriott",
    "st regis hotel": "Marriott",
    "courtyard marriott": "Marriott",
    "fairfield inn": "Marriott",
    "hilton hotels": "Hilton",
    "hampton inn": "Hilton",
    "doubletree": "Hilton",
    "embassy suites": "Hilton",
    "waldorf astoria": "Hilton",
    "curio collection": "Hilton",
    "holiday inn": "IHG",
    "crowne plaza": "IHG",
    "intercontinental hotels": "IHG",
    "kimpton hotels": "IHG",
    "even hotels": "IHG",
    "days inn": "Wyndham",
    "super 8": "Wyndham",
    "la quinta": "Wyndham",
    "ramada": "Wyndham",
    "howard johnson": "Wyndham",
    "motel 6": "Accor",
    "sofitel": "Accor",
    "novotel": "Accor",
    "hyatt regency": "Hyatt",
    "park hyatt": "Hyatt",
    "grand hyatt": "Hyatt",
    "andaz hotels": "Hyatt",

    # AIRLINES
    "delta airlines": "Delta Airlines",
    "united airlines": "United Airlines",
    "american airlines": "American Airlines",
    "southwest airlines": "Southwest Airlines",
    "spirit airlines": "Spirit Airlines",
    "frontier airlines": "Frontier Airlines",
    "jetblue airways": "JetBlue",
    "alaska airlines": "Alaska Airlines",
    "sun country airlines": "Sun Country",

    # CAR RENTAL
    "hertz car rental": "Hertz",
    "enterprise rent a car": "Enterprise",
    "avis car rental": "Avis",
    "budget car rental": "Budget",
    "national car rental": "Enterprise",
    "alamo rent a car": "Enterprise",
    "dollar rent a car": "Hertz",
    "thrifty car rental": "Hertz",

    # HOME IMPROVEMENT
    "home depot tools": "Home Depot",
    "lowes hardware": "Lowes",
    "behr paint": "Home Depot",
    "husky tools": "Home Depot",
    "ryobi tools": "Home Depot",
    "milwaukee tool": "Milwaukee Tool",
    "dewalt": "Stanley Black & Decker",
    "black and decker": "Stanley Black & Decker",
    "stanley tools": "Stanley Black & Decker",
    "craftsman tools": "Stanley Black & Decker",
    "irwin tools": "Stanley Black & Decker",
    "lenox tools": "Stanley Black & Decker",

    # GAMING
    "playstation": "Sony",
    "ps5": "Sony",
    "ps4": "Sony",
    "xbox series x": "Microsoft",
    "xbox one": "Microsoft",
    "nintendo switch": "Nintendo",
    "nintendo": "Nintendo",
    "mario games": "Nintendo",
    "zelda games": "Nintendo",
    "pokemon": "Nintendo",
    "call of duty": "Activision Blizzard",
    "activision": "Activision Blizzard",
    "world of warcraft": "Activision Blizzard",
    "overwatch": "Activision Blizzard",
    "candy crush": "Activision Blizzard",
    "ea sports": "Electronic Arts",
    "fifa game": "Electronic Arts",
    "madden nfl": "Electronic Arts",
    "the sims": "Electronic Arts",
    "apex legends": "Electronic Arts",
    "fortnite": "Epic Games",
    "roblox": "Roblox Corporation",
    "minecraft": "Microsoft",
    "grand theft auto": "Take-Two Interactive",
    "rockstar games": "Take-Two Interactive",
    "nba 2k": "Take-Two Interactive",

    # STREAMING
    "netflix": "Netflix",
    "spotify": "Spotify",
    "apple music": "Apple",
    "amazon prime video": "Amazon",
    "hbo max": "Warner Bros Discovery",
    "disney plus": "Disney",
    "hulu streaming": "Disney",
    "peacock tv": "Comcast",
    "paramount plus": "Paramount",
    "showtime": "Paramount",
    "paramount network": "Paramount",
    "mtv": "Paramount",
    "comedy central": "Paramount",
    "nickelodeon": "Paramount",
    "bet network": "Paramount",
    "vh1": "Paramount",

    # RIDESHARE / DELIVERY
    "uber rides": "Uber",
    "uber eats": "Uber",
    "lyft rides": "Lyft",
    "doordash delivery": "DoorDash",
    "grubhub delivery": "Grubhub",
    "instacart delivery": "Instacart",
    "shipt delivery": "Shipt",
    "postmates": "Uber",

    # OFFICE SUPPLIES
    "staples office": "Staples",
    "office depot": "Office Depot",
    "officemax": "Office Depot",

    # HEALTHCARE SERVICES
    "cvs pharmacy": "CVS Health",
    "cvs minute clinic": "CVS Health",
    "aetna insurance": "CVS Health",
    "walgreens pharmacy": "Walgreens",
    "duane reade": "Walgreens",
    "rite aid pharmacy": "Rite Aid",

    # MISCELLANEOUS WELL-KNOWN BRANDS
    "clorox bleach": "Clorox",
    "clorox": "Clorox",
    "pine sol": "Clorox",
    "pine-sol": "Clorox",
    "liquid plumr": "Clorox",
    "liquid-plumr": "Clorox",
    "formula 409": "Clorox",
    "glad trash bags": "Clorox",
    "hidden valley ranch": "Clorox",
    "kingsford charcoal": "Clorox",
    "burt's bees": "Clorox",
    "burts bees": "Clorox",
    "renew life": "Clorox",
    "rainbow light vitamins": "Clorox",

    "rubbermaid": "Newell Brands",
    "sharpie": "Newell Brands",
    "paper mate": "Newell Brands",
    "expo markers": "Newell Brands",
    "coleman camping": "Newell Brands",
    "jostens": "Newell Brands",
    "mr coffee": "Newell Brands",
    "sunbeam": "Newell Brands",
    "oster": "Newell Brands",
    "calphalon": "Newell Brands",
    "yankee candle": "Newell Brands",
    "elmer's glue": "Newell Brands",
    "x-acto": "Newell Brands",
    "contigo water bottle": "Newell Brands",
    "marmot outdoor": "Newell Brands",

    "hamilton beach": "Hamilton Beach",
    "proctor silex": "Hamilton Beach",

    "instant pot": "Instant Brands",
    "pyrex": "Instant Brands",
    "corelle": "Instant Brands",

    "keurig": "Keurig Dr Pepper",
    "dr pepper": "Keurig Dr Pepper",
    "snapple": "Keurig Dr Pepper",
    "7up soda": "Keurig Dr Pepper",
    "a&w root beer": "Keurig Dr Pepper",
    "canada dry": "Keurig Dr Pepper",
    "mott's juice": "Keurig Dr Pepper",
    "bai drinks": "Keurig Dr Pepper",
    "green mountain coffee": "Keurig Dr Pepper",
    "newman's own coffee": "Keurig Dr Pepper",
    "laughing man coffee": "Keurig Dr Pepper",
}

def get_product_company(product_name):
    """Look up parent company for a product name"""
    key = product_name.lower().strip()
    
    # Direct match
    if key in PRODUCT_MAP:
        return {"found": True, "product": product_name, "company": PRODUCT_MAP[key]}
    
    # Partial match — check if any product key is contained in the search term
    for product, company in PRODUCT_MAP.items():
        if product in key:
            return {"found": True, "product": product.title(), "company": company}
    
    return {"found": False}
